const constants = {
    ACCOUNT: "ACCOUNT",
    UPGRADE_ACCOUNT: "UPGRADE_ACCOUNT",
    GROUPS: "GROUPS",
    GENRES: "GENRES",
    CREATE_GROUP: "CREATE_GROUP",
    UPDATE_GROUP: "UPDATE_GROUP",
    CREATE_GENRE: "CREATE_GENRE",
    CREATE_SUBMISSION: "CREATE_SUBMISSION",
    UPDATE_SUBMISSION: "UPDATE_SUBMISSION",
    CREATE_REVIEW: "CREATE_REVIEW"
}